# Generated by Django 3.0.4 on 2023-10-06 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_insertdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treemenu',
            options={'verbose_name': 'Menu item', 'verbose_name_plural': 'Menu items'},
        ),
        migrations.AlterModelOptions(
            name='treemenucategory',
            options={'verbose_name': 'Menu category', 'verbose_name_plural': 'Menu categories'},
        ),
        migrations.AlterField(
            model_name='treemenu',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TreeMenuCategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='treemenu',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='treemenu',
            name='parent',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.TreeMenu', verbose_name='Parent element'),
        ),
        migrations.AlterField(
            model_name='treemenu',
            name='path',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='treemenucategory',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='treemenucategory',
            name='verbose_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Verbose name'),
        ),
    ]
